name: uyoung
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.3.2
  google_maps_flutter: ^2.6.0
  image_picker: ^1.2.1
  file_picker: ^10.3.7
  table_calendar: ^3.0.9
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/memory/
    - assets/images/memory/alcohol/
    - assets/images/memory/couple/
    - assets/images/memory/dolphin/
    - assets/images/memory/europe/
    - assets/images/memory/japan/
    # - assets/images/memory/kalchae/
    - assets/images/memory/shangkong/
  fonts:
    - family: memomentKkukkkuk
      fonts:
        - asset: assets/fonts/memomentKkukkkuk.ttf
